"use client"

import { useEffect, useState } from "react"
import { motion } from "framer-motion"
import Link from "next/link"
import type { Customer } from "@medusajs/medusa"
import DesignLightbox from "./design-lightbox"
import LikeButton from "./like-button"
import type { GeneratedDesign } from "../types"

interface ShowcaseDesign {
  id: string
  imageUrl: string
  prompt: string
  style: string
  occasion: string
  flavor: string
  likeCount: number
  commentCount: number
  viewCount: number
  isLiked: boolean
  createdAt: string
}

interface Props {
  customer: Omit<Customer, "password_hash"> | null
}

const OCCASION_FILTERS = [
  { value: "", label: "All" },
  { value: "Birthday", label: "🎂 Birthday" },
  { value: "Wedding", label: "💍 Wedding" },
  { value: "Kids", label: "👶 Kids" },
  { value: "Anniversary", label: "💝 Anniversary" },
  { value: "Festival", label: "🎪 Festival" },
  { value: "Special", label: "🎁 Special" },
]

export default function ShowcaseGallery({ customer }: Props) {
  const isLoggedIn = Boolean(customer)
  const [designs, setDesigns] = useState<ShowcaseDesign[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState("")

  // Lightbox
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [lightboxIndex, setLightboxIndex] = useState(0)

  useEffect(() => {
    setLoading(true)
    const params = new URLSearchParams({ limit: "8", sort: "popular" })
    if (filter) params.set("occasion", filter)

    fetch(`/api/ai-cake-studio-showcase?${params}`)
      .then((r) => r.json())
      .then((data) => {
        if (data.designs && data.designs.length > 0) {
          setDesigns(data.designs)
        }
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [filter])

  const handleUsePrompt = (prompt: string) => {
    const studio = document.getElementById("ai-studio")
    if (studio) {
      studio.scrollIntoView({ behavior: "smooth" })
      window.dispatchEvent(
        new CustomEvent("use-showcase-prompt", { detail: { prompt } })
      )
    }
  }

  // Skip the prompt entirely — adopt this exact generated cake and jump
  // straight to picking weight/message/add-ons for it.
  const handleUseCake = (design: ShowcaseDesign) => {
    const studio = document.getElementById("ai-studio")
    if (studio) {
      window.dispatchEvent(
        new CustomEvent("use-showcase-cake", {
          detail: {
            id: design.id,
            imageUrl: design.imageUrl,
            style: design.style,
            occasion: design.occasion,
            flavor: design.flavor,
            prompt: design.prompt,
          },
        })
      )
    }
  }

  // Convert to GeneratedDesign format for lightbox
  const lightboxDesigns: GeneratedDesign[] = designs.map((d) => ({
    id: d.id,
    title: `${d.style}${d.occasion ? " · " + d.occasion : ""} Cake`,
    description: d.prompt,
    gradient: "from-violet-400 via-purple-300 to-indigo-400",
    style: d.style,
    liked: false,
    imageUrl: d.imageUrl,
  }))

  // Don't render section if no designs and not loading
  if (!loading && designs.length === 0) return null

  return (
    <section className="px-4 py-10 sm:px-6 lg:px-12">
      <div className="mx-auto max-w-7xl">

        {/* Header */}
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="font-heading text-2xl font-bold text-slate-900 sm:text-3xl lg:text-4xl">
              Community Creations
            </h2>
            <p className="mt-1 text-sm text-slate-500">
              Real designs generated by users — get inspired or use their prompt
            </p>
          </div>
          <Link
            href="/ai-cake-studio/gallery"
            className="text-sm font-semibold text-violet-600 transition hover:text-violet-700"
          >
            View all →
          </Link>
        </div>

        {/* Occasion filters */}
        <div className="mb-5 flex flex-wrap gap-2">
          {OCCASION_FILTERS.map((f) => (
            <button
              key={f.value}
              type="button"
              onClick={() => setFilter(f.value)}
              className={`rounded-full px-3 py-1.5 text-xs font-semibold transition ${
                filter === f.value
                  ? "bg-violet-600 text-white"
                  : "border border-violet-200 bg-white text-violet-700 hover:border-violet-400"
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>

        {/* Loading state */}
        {loading && (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {[1, 2, 3, 4].map((n) => (
              <div
                key={n}
                className="h-64 animate-pulse rounded-2xl border border-violet-100 bg-violet-50"
              />
            ))}
          </div>
        )}

        {/* Design grid */}
        {!loading && designs.length > 0 && (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {designs.map((design, index) => (
              <motion.article
                key={design.id}
                initial={{ opacity: 0, y: 18 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: index * 0.05 }}
                className="group overflow-hidden rounded-2xl border border-violet-100 bg-white shadow-sm transition hover:shadow-md"
              >
                {/* Image */}
                <div
                  className="relative aspect-square cursor-pointer overflow-hidden bg-gradient-to-br from-violet-100 to-purple-50"
                  onClick={() => {
                    setLightboxIndex(index)
                    setLightboxOpen(true)
                  }}
                >
                  <img
                    src={design.imageUrl}
                    alt={`${design.style} ${design.occasion || ""} cake design`}
                    className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                    loading="lazy"
                  />

                  {/* Hover overlay */}
                  <div className="absolute inset-0 flex items-center justify-center bg-black/0 transition group-hover:bg-black/20">
                    <span className="rounded-full bg-white/90 px-3 py-1 text-xs font-semibold text-violet-700 opacity-0 transition group-hover:opacity-100">
                      View full
                    </span>
                  </div>

                  {/* Engagement badges */}
                  <div className="absolute bottom-2 left-2 flex gap-1.5">
                    <LikeButton
                      designId={design.id}
                      initialLiked={design.isLiked}
                      initialCount={design.likeCount}
                      isLoggedIn={isLoggedIn}
                    />
                    {design.commentCount > 0 && (
                      <span className="rounded-full bg-white/90 px-2 py-0.5 text-[10px] font-bold text-slate-600 backdrop-blur-sm">
                        💬 {design.commentCount}
                      </span>
                    )}
                  </div>
                </div>

                {/* Info */}
                <div className="p-3">
                  <div className="mb-2 flex flex-wrap gap-1">
                    <span className="rounded-full bg-violet-50 px-2 py-0.5 text-[10px] font-semibold text-violet-700">
                      {design.style}
                    </span>
                    {design.occasion && (
                      <span className="rounded-full bg-purple-50 px-2 py-0.5 text-[10px] font-semibold text-purple-700">
                        {design.occasion}
                      </span>
                    )}
                  </div>

                  {/* Truncated prompt */}
                  <p className="line-clamp-2 text-xs text-slate-500 leading-relaxed">
                    {design.prompt}
                  </p>

                  {/* Use this prompt / Use this cake — side by side on
                      larger screens, compact icon+word pair on mobile */}
                  <div className="mt-2 flex gap-1.5">
                    <button
                      type="button"
                      onClick={() => handleUsePrompt(design.prompt)}
                      className="flex-1 rounded-xl border border-violet-200 bg-violet-50 py-1.5 text-[11px] font-semibold text-violet-700 transition hover:bg-violet-100"
                    >
                      <span className="hidden sm:inline">✨ Use this prompt</span>
                      <span className="sm:hidden">✨ Prompt</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => handleUseCake(design)}
                      className="flex-1 rounded-xl border border-emerald-200 bg-emerald-50 py-1.5 text-[11px] font-semibold text-emerald-700 transition hover:bg-emerald-100"
                    >
                      <span className="hidden sm:inline">🎂 Use this cake</span>
                      <span className="sm:hidden">🎂 Cake</span>
                    </button>
                  </div>
                </div>
              </motion.article>
            ))}
          </div>
        )}

        {/* View all CTA */}
        {!loading && designs.length > 0 && (
          <div className="mt-6 text-center">
            <Link
              href="/ai-cake-studio/gallery"
              className="inline-flex items-center gap-2 rounded-xl border border-violet-200 bg-white px-5 py-2.5 text-sm font-semibold text-violet-700 transition hover:bg-violet-50"
            >
              View all community designs →
            </Link>
          </div>
        )}
      </div>

      {/* Lightbox */}
      <DesignLightbox
        open={lightboxOpen}
        onClose={() => setLightboxOpen(false)}
        designs={lightboxDesigns}
        startIndex={lightboxIndex}
        isLoggedIn={isLoggedIn}
      />
    </section>
  )
}
