import type { Metadata } from "next"
import Link from "next/link"

import { ENTITY, LEGAL_PENDING } from "@lib/constants/legal"
import { Callout, LegalShell, List, Section } from "@modules/legal/components/legal-shell"

export const metadata: Metadata = {
  alternates: { canonical: "/terms" },
  title: "Terms of Service",
  description:
    "The terms that apply when you use CrossFriend to order cakes and celebration products from local bakers, or to design a cake in the AI Cake Studio.",
}

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      summary="CrossFriend is a marketplace. When you order, your contract for the food itself is with the baker who makes it — we run the platform, take the payment and support the order."
    >
      <Section n={1} title="Who we are">
        <p>
          {ENTITY.brand} is operated by {ENTITY.legalName}, registered at {ENTITY.address}.
        </p>
        <p className="text-grey-50">
          GST: {ENTITY.gst} · CIN: {ENTITY.cin}
        </p>
        <p>
          By using {ENTITY.website} you agree to these terms. If you do not agree with them, please
          do not use the service.
        </p>
      </Section>

      <Section n={2} title="What CrossFriend is">
        <p>
          CrossFriend is an online marketplace that connects you with independent local bakers and
          sellers. We are an <strong>intermediary</strong> under the Information Technology Act,
          2000 and the rules made under it.
        </p>
        <Callout>
          <strong>This matters for who is responsible for what.</strong> The baker prepares the food,
          holds the food licence for it, and is responsible for its quality, safety, ingredients and
          allergen information. CrossFriend is responsible for the platform, the ordering experience,
          payment handling and support.
        </Callout>
        <p>
          We do not manufacture, cook or pack the products sold through CrossFriend, except where a
          listing explicitly identifies CrossFriend as the seller.
        </p>
      </Section>

      <Section n={3} title="Your account">
        <List
          items={[
            "You must be at least 18 years old to place an order.",
            "You sign in with your mobile number and a one-time password. Keep access to that number secure — anyone who can receive your OTP can access your account.",
            "You are responsible for the accuracy of the delivery address, contact number and any message you ask us to put on a cake.",
            "Tell us promptly at " + ENTITY.supportEmail + " if you believe your account has been used without your permission.",
          ]}
        />
      </Section>

      <Section n={4} title="Placing an order">
        <p>
          Adding an item to your cart is not an order. An order is placed when you complete checkout
          and is accepted when the baker confirms it. If a baker cannot accept your order, we will
          tell you and refund you in full.
        </p>
        <List
          items={[
            "Prices shown include applicable taxes unless stated otherwise. Delivery charges, if any, are shown before you pay.",
            "Cakes are made to order. Preparation time varies by baker and is shown on the product before you order.",
            <>
              Cancellation and refund rules are set out in our{" "}
              <Link href="/refund-policy" className="text-cf-orange underline">
                Refunds &amp; Cancellations policy
              </Link>
              .
            </>,
            <>
              Delivery areas, timings and cut-offs are set out in our{" "}
              <Link href="/shipping-policy" className="text-cf-orange underline">
                Shipping &amp; Delivery policy
              </Link>
              .
            </>,
          ]}
        />
        <p>
          Handmade food varies. Colour, decoration and finish may differ slightly from the photograph
          on a listing. Significant differences are covered by our refund policy; minor variation is
          a normal characteristic of food made by hand.
        </p>
      </Section>

      <Section n={5} title="AI Cake Studio">
        <p>
          The AI Cake Studio lets you describe a cake and generates a design image from your
          description. Please read this section carefully, because a generated image is a{" "}
          <strong>design concept, not a photograph of a product</strong>.
        </p>
        <List
          items={[
            "The image is generated by an artificial intelligence model. It shows an idea, not the cake you will receive.",
            "A baker will interpret the design using real ingredients and real technique. Some designs cannot be reproduced exactly, or at all, and a baker may decline or propose changes.",
            "Your description is sent to third-party AI providers to produce the image. Do not include personal, confidential or sensitive information in a prompt.",
            "You may use designs you generate for your own personal, non-commercial purposes. You grant us a licence to store them and, if you choose to share a design publicly, to display it in our community gallery.",
            "Do not generate content that infringes someone's copyright or trade mark, depicts a real person without their consent, or is unlawful, hateful, sexual or otherwise offensive.",
          ]}
        />
        <Callout>
          Prices quoted in the Studio are estimates based on the options you select. The final price
          is confirmed before you pay.
        </Callout>
      </Section>

      <Section n={6} title="Community gallery">
        <p>
          If you share a design to the community gallery, you allow other users to see it and to use
          it as a starting point for their own designs. You can make a shared design private again at
          any time from the Studio.
        </p>
        <p>
          We may remove any design, comment or account that breaches these terms, without notice
          where the content is unlawful or harmful.
        </p>
      </Section>

      <Section n={7} title="Payment">
        <p>
          Payments are processed by third-party payment providers. We do not store your full card
          details. You are responsible for any charges your bank or card issuer applies.
        </p>
        <p>
          Where a payment fails or is reversed after an order has been prepared, we may recover the
          amount owed and may suspend your account until it is settled.
        </p>
      </Section>

      <Section n={8} title="Things you must not do">
        <List
          items={[
            "Use CrossFriend for any unlawful purpose, or to order on someone else's behalf without their knowledge.",
            "Place fraudulent, abusive or repeatedly cancelled orders.",
            "Copy, scrape or republish listings, photographs or baker information from the platform.",
            "Attempt to interfere with the platform's security, or access another user's or baker's data.",
            "Abuse, threaten or harass a baker, a delivery partner or our staff.",
          ]}
        />
      </Section>

      <Section n={9} title="Our responsibility to you">
        <p>
          We will provide the platform with reasonable care and skill. We do not guarantee that the
          service will be uninterrupted or error-free.
        </p>
        <p>
          To the extent permitted by law, our total liability in connection with an order is limited
          to the amount you paid for that order. We are not liable for indirect or consequential loss
          — for example, the wider cost or disappointment of an event that did not go as planned.
        </p>
        <Callout>
          Nothing in these terms limits liability for death or personal injury caused by negligence,
          for fraud, or for anything else that cannot lawfully be limited. Your rights under the
          Consumer Protection Act, 2019 are unaffected.
        </Callout>
      </Section>

      <Section n={10} title="Bakers and sellers">
        <p>
          Bakers on CrossFriend are independent businesses, onboarded by invitation. Their
          obligations to us and to you are set out in the{" "}
          <Link href="/seller-terms" className="text-cf-orange underline">
            Baker Terms
          </Link>
          . A verification badge on a baker profile reflects checks we have carried out; it is not a
          guarantee of any particular outcome.
        </p>
      </Section>

      <Section n={11} title="Changes to these terms">
        <p>
          We may update these terms. The version that applies to an order is the version published
          when you placed it. Material changes will be notified on this page with a new date.
        </p>
      </Section>

      <Section n={12} title="Grievance Officer">
        <p>
          In accordance with the Information Technology Act, 2000 and the rules made under it, the
          Grievance Officer for {ENTITY.brand} is:
        </p>
        <p className="text-grey-90">
          {ENTITY.grievanceOfficer.name}
          <br />
          {ENTITY.legalName}
          <br />
          {ENTITY.address}
          <br />
          <a href={`mailto:${ENTITY.grievanceOfficer.email}`} className="text-cf-orange underline">
            {ENTITY.grievanceOfficer.email}
          </a>
        </p>
        <p>
          We aim to acknowledge complaints within 48 hours and resolve them within 30 days of
          receipt.
        </p>
      </Section>

      <Section n={13} title="Governing law">
        <p>
          These terms are governed by the laws of India. The courts at {ENTITY.jurisdiction} have
          exclusive jurisdiction over any dispute arising from them.
        </p>
        <p className="text-grey-50">
          GST and CIN registration details are marked &ldquo;{LEGAL_PENDING}&rdquo; and will be
          published here once issued.
        </p>
      </Section>
    </LegalShell>
  )
}
