import fs from "node:fs"
import path from "node:path"

import QRCode from "qrcode"
import React from "react"
import satori from "satori"
import sharp from "sharp"

/**
 * The branded share image: the design, untouched, with a designed strip beneath it.
 *
 * ── The problem it solves ──────────────────────────────────────────────────────────────────────
 * A cake photo forwarded on WhatsApp arrives with nothing attached to it. The caption is gone, the
 * link preview was regenerated by whoever received it and then lost when they screenshotted the
 * chat, and the sender is two forwards back. A local baker handed that photo asks "how big?" within
 * about ten seconds — and the answer, which we have, is nowhere on the thing they are looking at.
 *
 * Anything drawn into the pixels survives all of that. So the specs, the wordmark, the URL, a QR to
 * the design's own page and a short code go into the image itself, and the picture stops depending
 * on the message that carried it.
 *
 * ── Why the cake is never touched ──────────────────────────────────────────────────────────────
 * No watermark, no overlay, no logo across the frame. Two reasons, and the second is the one that
 * actually decides it:
 *
 * 1. A degraded image gives people a reason to crop it or regenerate it somewhere else, and an ugly
 *    image does not get shared — which defeats the entire purpose of branding it.
 * 2. The design page marks the raw image as an `ImageObject` with `contentUrl` for image search. A
 *    watermarked cake is a worse search result *and* a worse thing to hand a baker, so the two uses
 *    would be in conflict. Keeping the branding structural means one picture serves both: the raw
 *    file stays the canonical artwork, and this composition is what travels.
 *
 * ── Why satori and not @vercel/og ──────────────────────────────────────────────────────────────
 * scripts/generate-og-images.mjs documents at length why `@vercel/og` cannot be imported here: it
 * resolves its bundled wasm through a path that Node 22+ rejects outright, which is why every static
 * card in this repo is pre-rendered inside a Node 20 container instead. Production runs Node 20 and
 * would tolerate it, but `npm run build` would then fail for anyone on a current Node.
 *
 * satori has no such problem, and with `embedFont` it converts every glyph to a `<path>` — so the
 * SVG it produces is self-contained and sharp can rasterise it without a single font installed in
 * the container. That property is the whole reason this approach works at all.
 */

/**
 * One weight, registered under both 400 and 700.
 *
 * The repo ships exactly one face, and satori does not synthesise a bold — asking for 700 without
 * the file silently renders regular, which looks like a bug nobody can find. Registering the same
 * data under both weights makes that explicit, matches what generate-og-images.mjs already does, and
 * means hierarchy has to come from size, colour and letter-spacing. It does, below.
 */
const FONT_PATH = path.join(process.cwd(), "public", "fonts", "noto-sans-regular.ttf")

let fontData: Buffer | null = null
function font(): Buffer {
  if (!fontData) fontData = fs.readFileSync(FONT_PATH)
  return fontData
}

/**
 * The strip's palette.
 *
 * ── Why not brand purple ───────────────────────────────────────────────────────────────────────
 * The first version used the brand gradient, running from deep violet to #7B2FF7. It failed on
 * contrast at exactly the wrong end: the gradient is brightest on the right, which is where the
 * short code and — on the landscape card — the URL sit. Lilac on bright purple measured about
 * 1.8:1 and white on it about 3.9:1, against the 4.5:1 that ordinary text needs. The specs in white
 * were always legible; it was everything supporting them that dissolved.
 *
 * ── Why near-black rather than near-white ──────────────────────────────────────────────────────
 * Both fix the contrast. Near-black wins on a property specific to this product: cake photography is
 * overwhelmingly light — white marble, pale linen, bright kitchens — so a near-white strip meets the
 * photo with almost no boundary and needs a rule drawn along the top to hold its edge. Near-black
 * separates from every design the Studio produces without help, and leaves the cake as the only
 * saturated thing in the frame, which is what a person is meant to look at first.
 *
 * The brand purple survives as the accent on the wordmark and the URL, where it reads at about
 * 7.5:1 against this ground.
 *
 * The gradient is kept but travels between three near-blacks, so it reads as depth rather than as a
 * colour change — and no element's contrast depends on where along it that element happens to land.
 */
const BRAND = {
  from: "#141019",
  mid: "#1D1628",
  to: "#2A1F3D",
  wordmark: "#C3A3FF",
  specs: "#FFFFFF",
  url: "#C3A3FF",
  code: "#E9DDFF",
  /** The QR's dark modules. Matched to the ground so the code reads as printed on it, not stuck on. */
  qrDark: "#141019",
  /** The QR always sits on white. Scanners need the quiet zone and the polarity they expect. */
  qrCard: "#FFFFFF",
} as const

export interface ShareCardDesign {
  id: string
  imageUrl: string
  weight?: string | null
  tiers?: number | null
  shape?: string | null
  flavor?: string | null
  style?: string | null
  occasion?: string | null
}

export type ShareCardVariant = "story" | "og"

/**
 * The spec line, in the order a baker asks for it.
 *
 * Size first, because that is the question that gets asked in the first ten seconds and the one that
 * decides whether the rest of the conversation happens. Built from the fields that exist rather than
 * a template with blanks, so a design missing its flavour produces a shorter line instead of a
 * dangling separator.
 *
 * Price is deliberately absent, and must stay absent. It depends on the baker and the pincode, and a
 * number baked into a picture becomes a promise we cannot keep — made six weeks later, to somebody
 * we have never spoken to, on an image we cannot edit or recall.
 */
export function specLine(design: ShareCardDesign): string {
  const parts: string[] = []
  if (design.weight) parts.push(`${design.weight} kg`)
  if (design.tiers && design.tiers > 1) parts.push(`${design.tiers} tier`)
  if (design.shape) parts.push(design.shape.toLowerCase())
  if (design.flavor) parts.push(design.flavor.toLowerCase())
  if (design.style) parts.push(design.style.toLowerCase())
  /**
   * Occasion last, and only because the physical fields are so often empty.
   *
   * Sampling live designs: nearly all carry style and flavour, some carry tiers, and almost none
   * carry weight or shape — so the ideal line ("2 kg · 2 tier · round · chocolate · luxury") is not
   * what most real cards will print. "red velvet · luxury" alone is thin, and occasion is the one
   * field the Studio reliably captures that a reader would care about.
   *
   * It sits at the end rather than the front because it is context, not specification: the questions
   * a baker asks first are about size and flavour, and those keep the lead whenever they exist.
   */
  if (design.occasion) parts.push(design.occasion.toLowerCase())
  return parts.join("  ·  ")
}

/**
 * The short code printed beside the QR.
 *
 * A QR fails in exactly the situations these images end up in: a blurry re-forward, a photo of a
 * screen, a printout on a counter. A code someone can read aloud down a phone line never fails, and
 * it is the same id fragment the design's URL resolves on — so support can paste it straight into
 * the address bar.
 */
export function shortCode(designId: string): string {
  return `CF-${designId.replace(/-/g, "").slice(0, 8).toUpperCase()}`
}

/**
 * The QR, as a data URI.
 *
 * Error correction is set to M rather than L on purpose. WhatsApp recompresses every image it
 * carries, and a second or third forward is where a low-redundancy code stops scanning — which is
 * precisely the moment this whole idea is supposed to pay off. M costs a slightly denser code and
 * buys roughly 15% of the modules being recoverable.
 *
 * `margin: 1` rather than the default 4: the quiet zone is drawn by the white card behind it, so
 * four modules of built-in padding would shrink the code inside its own box for no benefit.
 */
async function qrDataUri(url: string, size: number): Promise<string> {
  return QRCode.toDataURL(url, {
    errorCorrectionLevel: "M",
    margin: 1,
    width: size,
    color: { dark: BRAND.qrDark, light: "#FFFFFF" },
  })
}

const el = (
  type: string,
  style: React.CSSProperties,
  ...children: React.ReactNode[]
) => React.createElement(type, { style }, ...children)

/** The wordmark, the specs and the address — the reading order, identical in both variants. */
function words(design: ShareCardDesign, specSize: number) {
  return [
    el(
      "div",
      { fontSize: 26, letterSpacing: 6, color: BRAND.wordmark, fontFamily: "Noto Sans" },
      "CROSSFRIEND"
    ),
    el(
      "div",
      {
        fontSize: specSize,
        color: BRAND.specs,
        marginTop: 14,
        lineHeight: 1.25,
        fontFamily: "Noto Sans",
      },
      specLine(design) || "AI cake design"
    ),
    el(
      "div",
      { fontSize: 26, color: BRAND.url, marginTop: 16, fontFamily: "Noto Sans" },
      "crossfriend.in"
    ),
  ]
}

/**
 * The QR and its short code.
 *
 * `flexShrink: 0` is not decoration. Without it the first version of this let a long spec line
 * squeeze the QR column until it ran off the right edge of the canvas — the code was cropped to
 * "CF-" and the QR lost a third of its modules, which is to say it silently stopped scanning. A
 * clipped QR looks like a design choice in a thumbnail and fails only in someone's hand.
 *
 * The code is white rather than the tint: it sits at the bright end of the gradient, where the tint
 * has almost no contrast left.
 */
function qrBlock(design: ShareCardDesign, qr: string, qrSize: number, stacked: boolean) {
  return el(
    "div",
    {
      display: "flex",
      flexDirection: stacked ? "column" : "row",
      alignItems: "center",
      flexShrink: 0,
    },
    el(
      "div",
      { display: "flex", backgroundColor: BRAND.qrCard, borderRadius: 16, padding: 10 },
      React.createElement("img", { src: qr, width: qrSize, height: qrSize })
    ),
    el(
      "div",
      {
        fontSize: 20,
        letterSpacing: 2,
        color: BRAND.code,
        fontFamily: "Noto Sans",
        ...(stacked ? { marginTop: 10 } : { marginLeft: 18 }),
      },
      shortCode(design.id)
    )
  )
}

/**
 * The branded area, in the shape the variant needs.
 *
 * Portrait puts it in a row beneath the cake, because a wide short strip has room side by side.
 * Landscape stacks it in a column beside the cake, because a tall narrow panel does not — trying to
 * force the row layout into 570px is what broke the first version.
 *
 * Hierarchy is carried by size, colour and letter-spacing rather than weight, since the repo ships
 * one face. The specs are the largest thing here because they are what the reader actually needs;
 * the wordmark is small and widely spaced; the address sits below in a tint so it reads as an
 * address rather than competing with the specification.
 */
function brandPanel(
  design: ShareCardDesign,
  qr: string,
  layout: { width: number; height: number; qrSize: number; specSize: number; column: boolean }
) {
  const ground = {
    display: "flex",
    width: layout.width,
    height: layout.height,
    backgroundColor: BRAND.mid,
    backgroundImage: `linear-gradient(120deg, ${BRAND.from} 0%, ${BRAND.mid} 55%, ${BRAND.to} 100%)`,
    padding: 40,
  } as const

  if (layout.column) {
    return el(
      "div",
      { ...ground, flexDirection: "column", justifyContent: "center" },
      ...words(design, layout.specSize),
      el(
        "div",
        { display: "flex", marginTop: 38 },
        qrBlock(design, qr, layout.qrSize, false)
      )
    )
  }

  /**
   * Explicit widths, not flex arithmetic.
   *
   * Both earlier attempts used `flexGrow` on the text with `flexShrink: 0` on the QR, and both let
   * the text column end up wider than the space available — pushing the QR past the right edge, where
   * it was silently cropped. `minWidth: 0` did not save it either.
   *
   * Rather than keep guessing at how satori resolves a contested row, the two columns are measured
   * here and add up to the width by construction. The QR is the fixed one because its size is the
   * thing that must not change: it is the only element on the card whose usefulness depends on its
   * dimensions in millimetres.
   */
  const inner = layout.width - 80
  const qrColumn = layout.qrSize + 40
  const gap = 30

  return el(
    "div",
    { ...ground, alignItems: "center" },
    el(
      "div",
      {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        width: inner - qrColumn - gap,
        marginRight: gap,
      },
      ...words(design, layout.specSize)
    ),
    el(
      "div",
      { display: "flex", width: qrColumn, justifyContent: "flex-end" },
      qrBlock(design, qr, layout.qrSize, true)
    )
  )
}

const LAYOUT = {
  /** Portrait, for the file that goes into a chat. Fills a phone screen. */
  story: { width: 1080, cake: 1080, strip: 340, qr: 150, spec: 42 },
  /**
   * Landscape, for link previews — 1.91:1 is what every platform crops toward.
   *
   * The cake is 540 rather than half the frame, so the panel gets 660 to work in. At 570 the spec
   * line and the QR could not both fit, and the QR was the one that lost.
   */
  og: { width: 1200, height: 630, cake: 700, qr: 140, spec: 38 },
} as const

const FETCH_TIMEOUT_MS = 10_000

async function fetchCake(imageUrl: string): Promise<Buffer> {
  const abort = new AbortController()
  const timer = setTimeout(() => abort.abort(), FETCH_TIMEOUT_MS)
  try {
    const res = await fetch(imageUrl, { signal: abort.signal, cache: "no-store" })
    if (!res.ok) throw new Error(`design image responded ${res.status}`)
    return Buffer.from(await res.arrayBuffer())
  } finally {
    clearTimeout(timer)
  }
}

async function rasterise(element: React.ReactNode, width: number, height: number) {
  const svg = await satori(element as React.ReactElement, {
    width,
    height,
    // Glyphs become <path> data, so the SVG carries its own type and sharp needs no font at all.
    embedFont: true,
    fonts: [
      { name: "Noto Sans", data: font(), weight: 400, style: "normal" },
      { name: "Noto Sans", data: font(), weight: 700, style: "normal" },
    ],
  })
  return sharp(Buffer.from(svg)).png().toBuffer()
}

/**
 * Compose the card.
 *
 * Throws on failure rather than returning a placeholder — the caller falls back to the raw design
 * image, which is exactly what shipped before this existed. A half-drawn card is worse than no card.
 */
export async function renderShareCard(
  design: ShareCardDesign,
  /**
   * The URL the QR encodes — and the only place a URL is used, since the strip prints the bare
   * "crossfriend.in" rather than the full address.
   *
   * Pass the **short** form. A design resolves on the trailing id fragment alone, so
   * `…/gallery/0d4b7d82` reaches the same page as the full prompt-bearing slug while encoding about
   * forty fewer characters. Fewer characters is a lower QR version, which is fewer and therefore
   * larger modules — and module size is exactly what decides whether a code still scans off a
   * twice-forwarded photo held at arm's length. The pretty URL belongs in the message, where a human
   * reads it; the QR is read by a camera and should be as sparse as it can be.
   */
  qrUrl: string,
  variant: ShareCardVariant = "story"
): Promise<Buffer> {
  const qr = await qrDataUri(qrUrl, variant === "story" ? LAYOUT.story.qr * 3 : LAYOUT.og.qr * 3)

  if (variant === "og") {
    const { width, height, cake, qr: qrSize, spec } = LAYOUT.og
    const panelWidth = width - cake

    const [cakeBytes, panelPng] = await Promise.all([
      fetchCake(design.imageUrl),
      rasterise(
        brandPanel(design, qr, {
          width: panelWidth,
          height,
          qrSize,
          specSize: spec,
          column: true,
        }),
        panelWidth,
        height
      ),
    ])

    const cakePng = await sharp(cakeBytes).resize(cake, height, { fit: "cover" }).png().toBuffer()

    return sharp({
      create: { width, height, channels: 4, background: BRAND.mid },
    })
      .composite([
        { input: cakePng, top: 0, left: 0 },
        { input: panelPng, top: 0, left: cake },
      ])
      .jpeg({ quality: 90 })
      .toBuffer()
  }

  const { width, cake, strip, qr: qrSize, spec } = LAYOUT.story
  const [cakeBytes, stripPng] = await Promise.all([
    fetchCake(design.imageUrl),
    rasterise(
      brandPanel(design, qr, {
        width,
        height: strip,
        qrSize,
        specSize: spec,
        column: false,
      }),
      width,
      strip
    ),
  ])

  const cakePng = await sharp(cakeBytes).resize(width, cake, { fit: "cover" }).png().toBuffer()

  return sharp({
    create: { width, height: cake + strip, channels: 4, background: BRAND.mid },
  })
    .composite([
      { input: cakePng, top: 0, left: 0 },
      { input: stripPng, top: cake, left: 0 },
    ])
    .jpeg({ quality: 90 })
    .toBuffer()
}
