import { designSlug } from "./design-slug"

/**
 * Sharing a design: where the link points, and how the picture travels with it.
 *
 * ── The two things this fixes ──────────────────────────────────────────────────────────────────
 * **The link went to the wrong page.** The share sheet used `window.location.href`, which on the
 * Studio is `/ai-cake-studio` — the generator. So someone sent a cake and their friend arrived at an
 * empty prompt box with no idea what they were meant to be looking at. Every design already has its
 * own page, built for exactly this, and the share path simply never used it.
 *
 * **No picture was ever sent.** `navigator.share({ title, text, url })` carries no image. On
 * WhatsApp that renders as a line of text and a link preview, so the only way a cake reached anybody
 * was if the sender took a screenshot themselves. The image is the whole point of a cake design; it
 * should not depend on the customer thinking to screenshot it.
 *
 * ── Why the file matters more than the link ────────────────────────────────────────────────────
 * A link preview is generated by the receiving app, from the page, at the moment of sending. Forward
 * that message on and the preview is regenerated; forward a screenshot of it and the link is gone
 * entirely. A shared *file* is the message. It survives forwarding, saving, re-sending weeks later,
 * and being shown to a baker across a counter — which is where these actually end up.
 *
 * So both are sent: the file so the cake always arrives, and the URL so there is a way back.
 */

/** What the share path needs to know about a design. Deliberately smaller than GeneratedDesign. */
export interface ShareableDesign {
  /** The server-side `ai_studio.cake_designs` id. Absent until the design is persisted. */
  designId?: string
  /** The human label — "Elegant · Birthday Cake". Used in the message, never in the URL. */
  title: string
  /**
   * The prompt behind the design, when the client has it.
   *
   * Only used to spell the URL, and only the trailing id fragment is ever read when resolving — so
   * any prose here produces a working link. `title` must still not be substituted for it: "Elegant ·
   * Birthday Cake" describes every third design on the site, while the prompt is the phrase somebody
   * would actually search for, which is the entire reason these pages have their own URLs.
   *
   * The page is written to redirect a non-canonical spelling to its own, though that redirect is not
   * currently firing in production. Nothing here depends on it: the words are decoration either way.
   */
  prompt?: string
  imageUrl?: string
  /**
   * False only when the customer has actively turned sharing off.
   *
   * Designs are created public, so undefined means public. This is not a default chosen for
   * convenience — it matches what the backend does on insert, and treating "unknown" as private
   * would suppress the design link for every design that has not been touched.
   */
  isPublic?: boolean
}

/**
 * The design's own page, or null when there is nowhere useful to point.
 *
 * Two cases return null, for different reasons:
 *
 * - **No `designId`.** The design exists only in this browser and has not been persisted, so no page
 *   exists to link to yet.
 * - **The customer turned sharing off.** The gallery page stops serving a design within the hour of
 *   it being made private, so the link becomes a dead end — and a dead end sent to a friend is worse
 *   than a link to the Studio. Prompts routinely name the recipient ("Happy birthday Priya"), which
 *   is why that setting exists; quietly linking past it would leak the thing the toggle protects.
 */
export function designPageUrl(design: ShareableDesign, origin: string): string | null {
  if (!design.designId) return null
  if (design.isPublic === false) return null

  // No prompt means designSlug falls back to the id alone, which resolves perfectly well — the page
  // reads only the trailing fragment and then redirects to its own spelling. A bare-id URL that
  // becomes descriptive on arrival beats a descriptive URL that describes the wrong thing.
  const slug = designSlug({ id: design.designId, prompt: design.prompt ?? "" })
  return `${origin}/ai-cake-studio/gallery/${slug}`
}

/**
 * The message body.
 *
 * The URL is passed separately to `navigator.share`, which appends it itself — repeating it in the
 * text produces the link twice in WhatsApp. It is only interpolated for the manual WhatsApp fallback
 * below, where nothing else would carry it.
 */
export function designShareText(
  design: ShareableDesign,
  context: { occasion?: string; style?: string },
  options: { includeUrl?: string | null } = {}
): string {
  const spec = [context.occasion, context.style && `${context.style} style`]
    .filter(Boolean)
    .join(" · ")

  const lines = [`🎂 Look at this "${design.title}" I designed on CrossFriend!`]
  if (spec) lines.push(`✨ ${spec}`)
  lines.push("🎉 Design your own cake for free")

  if (options.includeUrl) lines.push(options.includeUrl)
  return lines.join("\n\n")
}

/** A filename the receiving app will show. Kept short, safe, and obviously ours. */
export function designFileName(design: ShareableDesign): string {
  const words = design.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40)
    .replace(/-+$/, "")

  return `crossfriend-${words || "cake-design"}.jpg`
}

/** Same-origin URL for the design's image, so the bytes can be read without a CORS grant. */
export function designImageProxyUrl(imageUrl: string): string {
  return `/api/ai-studio/image?url=${encodeURIComponent(imageUrl)}`
}

/**
 * Turn a design's image into a File the native share sheet will accept.
 *
 * Returns null rather than throwing on every failure path — an image that cannot be fetched is a
 * reason to fall back to sharing a link, not a reason to show an error. The caller cannot do
 * anything useful with the distinction between "offline", "404" and "not an image".
 */
export async function fetchDesignImageFile(
  design: ShareableDesign
): Promise<File | null> {
  if (!design.imageUrl || typeof fetch === "undefined") return null

  try {
    const res = await fetch(designImageProxyUrl(design.imageUrl), { cache: "force-cache" })
    if (!res.ok) return null

    const blob = await res.blob()
    if (!blob.size || !blob.type.startsWith("image/")) return null

    return new File([blob], designFileName(design), { type: blob.type })
  } catch {
    return null
  }
}

/**
 * Whether this browser will actually accept these files.
 *
 * `navigator.share` existing says nothing about file support — desktop Safari and several Android
 * browsers expose `share` but reject a payload containing `files` with a TypeError. `canShare` with
 * the real files is the only reliable test, and it must be given the actual File objects rather than
 * a placeholder, because implementations check type and size.
 */
export function canShareFiles(files: File[]): boolean {
  if (typeof navigator === "undefined") return false
  const nav = navigator as Navigator & { canShare?: (data: ShareData) => boolean }
  if (typeof nav.share !== "function" || typeof nav.canShare !== "function") return false

  try {
    return nav.canShare({ files })
  } catch {
    return false
  }
}

export type ShareOutcome = "shared" | "cancelled" | "unsupported" | "failed"

/**
 * Hand a design to the device's share sheet, picture included where possible.
 *
 * ── Why cancellation is not a failure ──────────────────────────────────────────────────────────
 * Dismissing the OS share sheet rejects the promise with an AbortError, which is indistinguishable
 * from a real failure unless the name is checked. The previous code caught everything and did
 * nothing, so a cancelled share silently fell through — here it is reported so the caller can close
 * the sheet rather than reopening a fallback the customer just dismissed.
 */
export async function shareDesign(
  design: ShareableDesign,
  payload: { text: string; url: string | null },
  /**
   * A file the caller already has.
   *
   * ── Why this is not simply fetched here ────────────────────────────────────────────────────────
   * Safari on iOS requires `navigator.share` to be reached while the browser still considers itself
   * inside the tap that triggered it. Awaiting a network request first spends that window, and the
   * share then rejects with NotAllowedError — on the platform where sharing a picture into WhatsApp
   * matters most, and only on real devices, so it survives desktop testing comfortably.
   *
   * Passing `undefined` means "fetch it yourself", which is correct on Android and desktop where no
   * such rule exists. Passing a File — or explicitly `null` — skips the await entirely, so
   * `navigator.share` is reached in the same task as the click.
   */
  prefetched?: File | null
): Promise<ShareOutcome> {
  if (typeof navigator === "undefined" || typeof navigator.share !== "function") {
    return "unsupported"
  }

  const file = prefetched !== undefined ? prefetched : await fetchDesignImageFile(design)
  const data: ShareData = {
    text: payload.text,
    ...(payload.url ? { url: payload.url } : {}),
  }

  // Files only if this browser confirms it will take them. Attaching them optimistically throws and
  // loses the share entirely, when a text-and-link share would have worked.
  if (file && canShareFiles([file])) {
    data.files = [file]
  }

  try {
    await navigator.share(data)
    return "shared"
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") return "cancelled"
    return "failed"
  }
}
